### ISSUE TITLE
some problems of main.cpp

### ISSUE THREAD

**Issue by deepwebney** [smartyfh/MAIC#1]
Hello author, thank you very much for sharing the code, but I have some questions and hope to get your help. First, the specific contents of path[10] and n[10] in main function are only declared in the code without specific data content. Second, can you explain the meaning of the parameters in detail?

**Comment by smartyfh** [comment]
> Hello author, thank you very much for sharing the code, but I have some questions and hope to get your help. First, the specific contents of path[10] and n[10] in main function are only declared in the code without specific data content. Second, can you explain the meaning of the parameters in detail?

Hi, thanks for reaching out. Path is the root directory of edges, attributes, etc. n means the number of nodes in a graph. You may refer to the load data function to see how the data is loaded, then you should be able to figure out what the data content looks like.

**Comment by deepwebney** [comment]
Thank you very much, but there is another question. What is the purpose of swapping data[i] and data[p] in Independent() of feature.cpp?

**Comment by mlangTse** [comment]
> Thank you very much, but there is another question. What is the purpose of swapping data[i] and data[p] in Independent() of feature.cpp?

Hi, the original dataset only contains tuples representing edges, how do you get the attributes of each vertex?
