### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by mlangTse** [smartyfh/MAIC#2]
The original dataset only contains tuples representing edges, how do you get the attributes of each vertex?

**Comment by smartyfh** [comment]
> The original dataset only contains tuples representing edges, how do you get the attributes of each vertex?

I can share the code with you via email.

**Comment by mlangTse** [comment]
> > The original dataset only contains tuples representing edges, how do you get the attributes of each vertex?
> 
> I can share the code with you via email.

that will be great, my email is 1501728654@qq.com
